on:
  push:
    branches: ["main"]

jobs:
  bach-hoa-si-fe-build:
    name: Build source code to Docker image
    runs-on: ubuntu-22.04 
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3

      - name: DockerHub Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build Image And Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/bach-hoa-si-fe:latest
  
  staging-fe-deploy:
    name: Deploy Staging FE Admin To Google Service Server For Testing
    runs-on: arisa-deploy
    needs: bach-hoa-si-fe-build
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
    steps:
    - name: Checkout Develop
      uses: actions/checkout@v3
    - name: DockerHub Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Stop BachHoaSi API
      run: docker compose -p bach-hoa-si-fe-test down bachhoasi-fe
    - name: Clean Old BachHoaSi Image
      run: docker rmi ${{secrets.DOCKER_USERNAME}}/bach-hoa-si-fe:latest
      continue-on-error: true
    - name: Deploy API
      run: docker compose -p bach-hoa-si-fe-test up -d bachhoasi-fe